
using System;
using System.Collections;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Text;
using Unity.VisualScripting;
using UnityEditor;
using UnityEngine;


public static class ExcelImporter 
{ 
    [MenuItem("Tools/ExcelTest/1. Read File")] 
    public static void ReadFile()
    {
        ImportCsv("Assets/04.Data/Test/Excel/Test.csv");
    }

    public static void ImportCsv(string path) 
    {      
        ScriptableObject listAsset  = FindTargetListAsset(path);

        //string text = File.ReadAllText(path);
        string text;
        using (FileStream stream = new FileStream(path, FileMode.Open, FileAccess.Read, FileShare.ReadWrite))
        {
            using StreamReader reader = new StreamReader(stream);
            text = reader.ReadToEnd();
        }
        string[] lines = text.Split('\n');
        string[] values;
        string[] headers = lines[0].Trim('\r').Split(",");

        string[] requiredHeaders = { "id", "codeName", "description", "displayName" };
        foreach (string requiredHeader in requiredHeaders)
        {
            if (!headers.Contains(requiredHeader))
            {
                Debug.LogError($"필수 헤더 누락: {requiredHeader}");
                return;
            }
        }
        

        Type listType = listAsset.GetType();
        Type dataType = listType.BaseType.GetGenericArguments()[0];

        FieldInfo baseListField = listType.GetField("baseList");       
        IList dataList = (IList)Activator.CreateInstance(baseListField.FieldType);

        
        StringBuilder sb = new StringBuilder();
        string enumName = dataType.Name.Replace("Data", "") + "Id";

        sb.AppendLine("// <auto-generated>");
        sb.AppendLine("// 이 파일은 자동 생성됩니다. 직접 수정하지 마세요.");
        sb.AppendLine("// </auto-generated>");
        sb.AppendLine();
        sb.AppendLine($"public enum {enumName}");
        sb.AppendLine("{");       


        for (int i = 1; i < lines.Length; i++) 
        {
            if (string.IsNullOrEmpty(lines[i])) continue;

            lines[i] = lines[i].TrimEnd('\r');
            values = lines[i].Split(',');

            BaseData data = (BaseData)Activator.CreateInstance(dataType);

            for (int col = 0; col < headers.Length; col++)
            {
                FieldInfo field = dataType.GetField(headers[col]);
                Debug.Log($"{dataType.Name}/ [{headers[col]}].");
                if (field == null)
                {
                    Debug.LogError($"{dataType.Name}에 [{headers[col]}] 필드가 없습니다.");
                    return;
                    
                }
                //object value = Convert.ChangeType(values[col], field.FieldType); 이 코드는 AnimationClip을 못 읽음.

                object value;

                if(typeof(UnityEngine.Object).IsAssignableFrom(field.FieldType))
                {
                    string assetPath = values[col].Trim();

                    if (string.IsNullOrWhiteSpace(assetPath))
                    {
                        value = null; //드디어 들어간 안전처리.
                    }
                    else
                    {
                        value = AssetDatabase.LoadAssetAtPath(assetPath, field.FieldType);

                        if (value == null)
                        {
                            Debug.LogError($"{field.FieldType.Name} is not found : {assetPath}");
                            return;
                        }
                    }
                }
                else
                {                    
                    value = Convert.ChangeType(values[col],field.FieldType);
                }

                /*
                if(field.FieldType == typeof(AnimationClip))
                {
                    string clipPath = values[col].Trim();
                    if(string.IsNullOrEmpty(clipPath))
                    {
                        value = null;
                    }
                    else
                    {
                        AnimationClip clip = AssetDatabase.LoadAssetAtPath<AnimationClip>(clipPath);

                        if(clipPath == null)
                        {
                            Debug.LogError("AnimationClip is not found : " + clipPath);
                            return;
                        }
                        value = clip;
                    }               

                }
                else
                {
                    value = Convert.ChangeType(values[col], field.FieldType);
                }
                */
                field.SetValue(data, value);

                if (col > 100)
                {
                    Debug.LogError("Loop guard triggered");
                    break;
                }
            }         
            dataList.Add(data);

            sb.AppendLine($"    {data.codeName} = {data.id.ToString()},");
        }        
        sb.AppendLine("}" );
        
        string GeneratePath = "Assets/01.Script/00.Enum,Interface,Structer/Generated/" + enumName + ".g.cs";
        string generateCode = sb.ToString();
        string directory = Path.GetDirectoryName(GeneratePath);

        if (!Directory.Exists(directory))
        {
            Directory.CreateDirectory(directory);
        }

        File.WriteAllText(GeneratePath, generateCode);
        AssetDatabase.ImportAsset(GeneratePath);
        Debug.Log($"{enumName} script 생성됨.");

        baseListField.SetValue(listAsset, dataList);

        EditorUtility.SetDirty(listAsset);
        AssetDatabase.SaveAssets();
    }

   


   
    public static ScriptableObject FindTargetListAsset(string csvPath)
    {

        string csvName = Path.GetFileNameWithoutExtension(csvPath);
        string targetDataTypeName = csvName + "Data";

        string[] guids = AssetDatabase.FindAssets("t:ScriptableObject");

        foreach (string guid in guids)
        {
            string assetPath = AssetDatabase.GUIDToAssetPath(guid);
            
            ScriptableObject asset = AssetDatabase.LoadAssetAtPath<ScriptableObject>(assetPath);

            if(asset == null) continue;

            Type listType = asset.GetType();
            Type baseType = listType.BaseType;

            if (baseType == null) continue;

            if (!baseType.IsGenericType) continue;

            if (baseType.GetGenericTypeDefinition() != typeof(BaseList<>)) continue;

            Type dataType = baseType.GetGenericArguments()[0];

            if (dataType.Name == targetDataTypeName)
            {
                return asset;
            }


        }
        return null;
    }



}